-- ================================================================
-- Generated by AI Data Engineer Agent
-- Ticket  : https://phdata.atlassian.net/browse/DEB-3
-- Title   : Development of table and data population procedure
-- Author  : madhumithac
-- Role    : DEV_SECREF_FR_ENGR_ROLE
-- Database: DEV_SECREFTEST_DB
-- Schema  : RAW
-- ================================================================

USE ROLE DEV_SECREF_FR_ENGR_ROLE;
USE DATABASE DEV_SECREFTEST_DB;
USE SCHEMA RAW;

-- ----------------------------------------------------------------
-- Table definition
-- ----------------------------------------------------------------
CREATE OR REPLACE TABLE DEV_SECREFTEST_DB.RAW.TEST_TABLE_DEB_3 (
    ID       INT,
    Name     VARCHAR(255),
    Amount   FLOAT
);

-- ================================================================
-- VALIDATION QUERIES
-- ================================================================

-- 1. Check table exists
--    DESC TABLE RAW.TEST_TABLE_DEB_3;

-- 2. Verify row count after loading
--    SELECT COUNT(*) FROM RAW.TEST_TABLE_DEB_3;
