-- ================================================================
-- Generated by AI Data Engineer Agent
-- Ticket  : https://your-org.atlassian.net/browse/DE-42
-- Title   : Development of Table and Data Population Procedure
-- Author  : Your Name
-- Role    : DEV_SECREF_FR_ENGR_ROLE
-- Database: DEV_SECREFTEST_DB
-- Schema  : RAW
-- ================================================================

-- ----------------------------------------------------------------
-- OBJECT 1: Table definition
-- ----------------------------------------------------------------
CREATE OR REPLACE TABLE RAW.AI_AGENT_TEST_TABLE_2 (
    ID       INT,
    Name     VARCHAR,
    Amount   FLOAT
);

-- ----------------------------------------------------------------
-- OBJECT 2: Population procedure
-- ----------------------------------------------------------------
CREATE OR REPLACE PROCEDURE RAW.P_FILL_AI_AGENT_TEST_TABLE_2()
RETURNS VARCHAR
LANGUAGE SQL
EXECUTE AS CALLER
AS '
DECLARE
    rows_inserted NUMBER := 0;
BEGIN
    -- Set query tag for observability in Snowflake query history
    ALTER SESSION SET QUERY_TAG = ''AI_AGENT_POPULATION_PROC'';

    INSERT INTO RAW.AI_AGENT_TEST_TABLE_2 (ID, Name, Amount)
    VALUES
        (1,  ''Alice'',   100.50),
        (2,  ''Bob'',     250.75),
        (3,  ''Charlie'', 320.00),
        (4,  ''Diana'',   175.25),
        (5,  ''Eve'',     450.90),
        (6,  ''Frank'',   210.60),
        (7,  ''Grace'',   390.85),
        (8,  ''Hank'',    125.40),
        (9,  ''Ivy'',     280.30),
        (10, ''Jack'',    340.15);

    rows_inserted := 10;

    -- Clear query tag
    ALTER SESSION SET QUERY_TAG = '''';

    RETURN ''Success: '' || rows_inserted || '' rows inserted into AI_AGENT_TEST_TABLE_2'';
END;
';

-- ================================================================
-- VALIDATION QUERIES
-- Run these manually in Snowflake to verify the implementation.
-- These map directly to the acceptance criteria in the Jira ticket.
-- ================================================================

-- 1. Check table exists
--    DESC TABLE RAW.AI_AGENT_TEST_TABLE_2;

-- 2. Check procedure exists
--    SHOW PROCEDURES LIKE 'P_FILL_AI_AGENT_TEST_TABLE_2' IN SCHEMA RAW;

-- 3. Call the procedure
--    CALL RAW.P_FILL_AI_AGENT_TEST_TABLE_2();

-- 4. Verify row count (expected: 10)
--    SELECT COUNT(*) FROM RAW.AI_AGENT_TEST_TABLE_2;

-- 5. Verify query tag in history
--    SELECT query_id, query_text, query_tag
--    FROM TABLE(INFORMATION_SCHEMA.QUERY_HISTORY())
--    WHERE query_tag = 'AI_AGENT_POPULATION_PROC'
--    ORDER BY start_time DESC
--    LIMIT 10;
