-- ================================================================
-- Generated by AI Data Engineer Agent
-- Ticket  : https://phdata.atlassian.net/browse/DEB-3
-- Title   : Development of table and data population procedure
-- Author  : madhumithac
-- Role    : DEV_SECREF_FR_ENGR_ROLE
-- Database: DEV_SECREFTEST_DB
-- Schema  : RAW
-- ================================================================

USE ROLE DEV_SECREF_FR_ENGR_ROLE;
USE DATABASE DEV_SECREFTEST_DB;
USE SCHEMA RAW;

-- ----------------------------------------------------------------
-- OBJECT 1: Table definition
-- ----------------------------------------------------------------
CREATE TABLE IF NOT EXISTS RAW.AI_AGENT_TEST_TABLE_2 (
    ID       INT,
    Name     VARCHAR(255),
    Amount   FLOAT
);

-- ----------------------------------------------------------------
-- OBJECT 2: Population procedure
-- ----------------------------------------------------------------
CREATE OR REPLACE PROCEDURE RAW.P_FILL_AI_AGENT_TEST_TABLE_2()
RETURNS VARCHAR
LANGUAGE SQL
EXECUTE AS CALLER
AS '
DECLARE
    rows_inserted NUMBER := 0;
BEGIN
    -- Set query tag for observability in Snowflake query history
    ALTER SESSION SET QUERY_TAG = ''AI_AGENT_POPULATION_PROC'';

    INSERT INTO RAW.AI_AGENT_TEST_TABLE_2 (ID, Name, Amount)
    VALUES
        (1,  ''Alice'',   100.50),
        (2,  ''Bob'',     250.75),
        (3,  ''Charlie'', 320.00),
        (4,  ''Diana'',   415.25),
        (5,  ''Eve'',     530.90),
        (6,  ''Frank'',   640.00),
        (7,  ''Grace'',   720.35),
        (8,  ''Hank'',    810.60),
        (9,  ''Ivy'',     905.45),
        (10, ''Jack'',    1050.80);

    rows_inserted := 10;

    -- Clear query tag
    ALTER SESSION SET QUERY_TAG = '''';

    RETURN ''Success: '' || rows_inserted || '' rows inserted into AI_AGENT_TEST_TABLE_2'';
END;
';

-- ----------------------------------------------------------------
-- Execute the procedure to populate the table
-- ----------------------------------------------------------------
CALL RAW.P_FILL_AI_AGENT_TEST_TABLE_2();

-- ================================================================
-- VALIDATION QUERIES
-- Run these manually in Snowflake to verify the implementation.
-- These map directly to the acceptance criteria in the Jira ticket.
-- ================================================================

-- 1. Check table exists
--    DESC TABLE RAW.AI_AGENT_TEST_TABLE_2;

-- 2. Check procedure exists
--    SHOW PROCEDURES LIKE 'P_FILL_AI_AGENT_TEST_TABLE_2' IN SCHEMA RAW;

-- 3. Call the procedure
--    CALL RAW.P_FILL_AI_AGENT_TEST_TABLE_2();

-- 4. Verify row count (expected: 10)
--    SELECT COUNT(*) FROM RAW.AI_AGENT_TEST_TABLE_2;

-- 5. Verify query tag in history
--    SELECT query_id, query_text, query_tag
--    FROM TABLE(INFORMATION_SCHEMA.QUERY_HISTORY())
--    WHERE query_tag = 'AI_AGENT_POPULATION_PROC'
--    ORDER BY start_time DESC
--    LIMIT 10;
