-- ================================================================
-- Generated by AI Data Engineer Agent
-- Ticket  : https://phdata.atlassian.net/browse/DEB-3
-- Title   : Development of table and data population procedure
-- Author  : madhumithac
-- Role    : DEV_SECREF_FR_ENGR_ROLE
-- Database: DEV_SECREFTEST_DB
-- Schema  : RAW
-- ================================================================

USE ROLE DEV_SECREF_FR_ENGR_ROLE;
USE DATABASE DEV_SECREFTEST_DB;
USE SCHEMA RAW;

-- ----------------------------------------------------------------
-- Population procedure
-- ----------------------------------------------------------------
CREATE OR REPLACE PROCEDURE RAW.P_FILL_AI_AGENT_TEST_TABLE_2()
RETURNS VARCHAR
LANGUAGE SQL
EXECUTE AS CALLER
AS '
DECLARE
    rows_inserted NUMBER := 0;
BEGIN
    -- Set query tag for observability in Snowflake query history
    ALTER SESSION SET QUERY_TAG = ''AI_AGENT_POPULATION_PROC'';

    INSERT INTO RAW.AI_AGENT_TEST_TABLE_2 (ID, Name, Amount)
    VALUES
        (1,  ''Alice'',   100.50),
        (2,  ''Bob'',     250.75),
        (3,  ''Charlie'', 320.00),
        (4,  ''Diana'',   415.25),
        (5,  ''Eve'',     530.80),
        (6,  ''Frank'',   620.40),
        (7,  ''Grace'',   710.95),
        (8,  ''Hank'',    805.60),
        (9,  ''Ivy'',     915.30),
        (10, ''Jack'',    1050.00);

    rows_inserted := 10;

    -- Clear query tag
    ALTER SESSION SET QUERY_TAG = '''';

    RETURN ''Success: '' || rows_inserted || '' rows inserted into AI_AGENT_TEST_TABLE_2'';
END;
';

-- ================================================================
-- VALIDATION QUERIES
-- ================================================================

-- 1. Check procedure exists
--    SHOW PROCEDURES LIKE ''P_FILL_AI_AGENT_TEST_TABLE_2'' IN SCHEMA RAW;

-- 2. Call the procedure
--    CALL RAW.P_FILL_AI_AGENT_TEST_TABLE_2();

-- 3. Verify query tag in history
--    SELECT query_id, query_text, query_tag
--    FROM TABLE(INFORMATION_SCHEMA.QUERY_HISTORY())
--    WHERE query_tag = ''AI_AGENT_POPULATION_PROC''
--    ORDER BY start_time DESC
--    LIMIT 10;
