-- ================================================================
-- Generated by AI Data Engineer Agent
-- Ticket  : https://phdata.atlassian.net/browse/DEB-3
-- Title   : Development of table and data population procedure
-- Author  : madhumithac
-- Role    : DEV_SECREF_FR_ENGR_ROLE
-- Database: DEV_SECREFTEST_DB
-- Schema  : RAW
-- ================================================================

USE ROLE DEV_SECREF_FR_ENGR_ROLE;
USE DATABASE DEV_SECREFTEST_DB;
USE SCHEMA RAW;

-- ----------------------------------------------------------------
-- Population procedure
-- ----------------------------------------------------------------
CREATE OR REPLACE PROCEDURE DEV_SECREFTEST_DB.RAW.P_TEST_PROC_DEB_3()
RETURNS VARCHAR
LANGUAGE SQL
EXECUTE AS CALLER
AS '
DECLARE
    rows_inserted NUMBER := 0;
BEGIN
    -- Set query tag for observability in Snowflake query history
    CALL SYSTEM$SET_QUERY_TAG(''DEB-3_P_TEST_PROC_DEB_3'');

    INSERT INTO RAW.TEST_TABLE_DEB_3 (ID, Name, Amount)
    VALUES
        (1,  ''Alice'',   100.50),
        (2,  ''Bob'',     250.75),
        (3,  ''Charlie'', 320.00),
        (4,  ''Diana'',   415.25),
        (5,  ''Eve'',     530.80),
        (6,  ''Frank'',   670.40),
        (7,  ''Grace'',   785.60),
        (8,  ''Hank'',    890.15),
        (9,  ''Ivy'',     945.30),
        (10, ''Jack'',    999.99);

    rows_inserted := 10;

    -- Clear query tag
    CALL SYSTEM$SET_QUERY_TAG('''');

    RETURN ''Success: '' || rows_inserted || '' rows inserted into TEST_TABLE_DEB_3'';
END;
';

-- ================================================================
-- VALIDATION QUERIES
-- ================================================================

-- 1. Check procedure exists
--    SHOW PROCEDURES LIKE ''P_TEST_PROC_DEB_3'' IN SCHEMA RAW;

-- 2. Call the procedure
--    CALL RAW.P_TEST_PROC_DEB_3();

-- 3. Verify query tag in history
--    SELECT query_id, query_text, query_tag
--    FROM TABLE(INFORMATION_SCHEMA.QUERY_HISTORY())
--    WHERE query_tag = ''DEB-3_P_TEST_PROC_DEB_3''
--    ORDER BY start_time DESC
--    LIMIT 10;
